= Fazendo o download do JBoss =
:author: Paulo Jerônimo
:email: pj@paulojeronimo.info

Logado como usuário +aluno+, em um shell aberto na máquina +base+ (HOST), execute:
[NOTE]
======
Para fazer o login como aluno, a partir do seu usuário, execute os comandos a seguir. Eles deverão ser repetidos em todos os próximos laboratórios.
[source,bash]
----
$ xhost +
$ sudo su - aluno
$ export DISPLAY=:0
----
======
[source,bash]
----
$ iniciar-script ~/curso-jboss/laboratorios/jboss-download
$ mkdir -p ~/Downloads
----
Abra o browser, conforme a seguir:
[source,bash]
----
$ firefox http://www.jboss.org/products/eap &> /dev/null &
----
Na página aberta, clique nos links "Download EAP 6.2", "Quickstarts" e "Maven Repo". Salve todos os arquivos no diretório +~/Downloads+. _Se você ainda não tiver uma conta no sistema do grupo JBoss, será necessário criar uma para fazer esse download._

.Nota para o instrutor:
[NOTE]
======
Para evitar a espera do download, os arquivos já estão baixados em +$HOME/Installers/Java/JBoss/EAP/6.2.0/+. Copie-os, para o diretório +~/Downloads+ e prossiga.
======
Volte ao shell e execute:
[source,bash]
----
$ d=~/curso-jboss/instaladores/jboss-eap/6.2.0
$ mkdir -p $d
----
Mova os arquivos baixados para o diretório do curso:
[source,bash]
----
$ mv ~/Downloads/jboss-eap-6.2.0* $d/
----
Verifique o sha1sum dos arquivos baixados, executando:
[source,bash]
----
$ cd $d
$ curl -L http://raw.github.com/paulojeronimo/livro-jboss/\
master/laboratorios/jboss-download/jboss-eap-6.2.0.sha1sum -O
$ sha1sum -c jboss-eap-6.2.0.sha1sum
----
Encerre a execução desse lab, executando:
[source,bash]
----
$ exit
----
