#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)
basedir=`d=$(dirname "$0"); cd "$d"; echo -n $PWD`
op=${1:-build}

__slides_build() {
   local p=$1
   [ -d slides ] && slides/build $p
}

__asciidoc() {
   local f=$1
   local cmd="asciidoc $f"

   echo "$cmd"; $cmd
}

_build() {
   find . -type f -name "*.asciidoc" ! -path './slides/*' | \
   while read f
   do 
      h=${f/asciidoc/html}
      [ ! -f "$h" ] && __asciidoc "$f"
      [ "$f" -nt "$h" ] && __asciidoc "$f"
   done
   __slides_build
}

_clean() {
   find . -type f -name "*.html" ! -path './slides/*' -delete
   __slides_build clean
}

_clean_all() {
   __slides_build clean_all
}

cd "$basedir"
_$op
