= Arquivos públicos do meu livro de JBoss =
:author: Paulo Jerônimo
:email: pj@paulojeronimo.info
:numbered:

Este repositório contém os arquivos públicos do livro de JBoss que *estou escrevendo*. Isso significa que as informações apresentadas aqui estão sujeitas a constantes mudanças, até a geração de releases desse livro.

Esse livro também é a base para um link:curso.asciidoc[curso que ministro, a distância, sobre o JBoss EAP em ambientes de produção] (link:curso.html[HTML]). Se você deseja mais detalhes a respeito de como adquirir o livro e/ou ingressar no curso, clique nos links apresentados nesse parágrafo.

Todo o material que está publicado nesse repositório é livre para uso sem fins comerciais, respeitando-se os direitos de autoria. Nele você encontrará o texto de alguns dos capítulos do meu livro, além dos link:slides/README.asciidoc[slides] (link:slides/README.html[HTML]) que criei para apresentar tópicos do curso e de todos os comandos executados nos laboratórios (labs). Sobre esses labs, entretanto, você notará que apenas os iniciais contém explicações detalhadas. A maioria das explicações, porém, assim como a ordem de execução dos labs, não está aqui e só é disponibilizada para aqueles que obtêm o livro.

Você pode utilizar o conteúdo desse repositório de duas maneiras:

. Pela Internet, visualizando o conteúdo através do http://github.com/paulojeronimo/livro-jboss[repositório no GitHub]. Nesse caso, os links "_(HTML)_" não estão disponíveis;
. Em seu computador, baixando esse repositório e gerando os arquivos HTML através do http://www.methods.co.nz/asciidoc/[AsciiDoc], ou do http://asciidoctor.org[Asciidoctor]. Para gerar através do AsciiDoc, execute (_passos no Fedora_):
[source,bash]
----
$ git clone https://github.com/paulojeronimo/livro-jboss.git
$ cd livro-jboss
$ sudo yum -y install asciidoc python-pygments
$ ./build
$ firefox ./README.html &> /dev/null &
----

Esse repositório contém uma sequência de labs gratuitos que você deve trilhar se desejar continuar o curso. Essa sequência compreende todos os labs iniciais cujos links estão disponíveis em "*Tópicos do curso*" da página link:curso.asciidoc[] (link:curso.html[HTML]).
