#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)
basedir=`d=$(dirname "$0"); cd "$d"; echo -n $PWD`
pages_builder="${pages_builder:-asciidoc}"
op=${1:-build}

__build_README() {
   local cmd="$pages_builder README.asciidoc"
   echo "$cmd"; $cmd
}

__build_SLIDES() {
   local f=$1
   local cmd="asciidoctor -b dzslides -T asciidoctor-backends/slim/dzslides $f"

   echo "$cmd"; $cmd
}

_build() {
   [ -f README.html ] || __build_README
   [ README.asciidoc -nt README.html ] && __build_README

   for d in asciidoctor-backends dzslides
   do
      [ -d $d ] || git clone https://github.com/paulojeronimo/$d.git
   done

   find . -type f -name '*.asciidoc' ! \( \
   -name README.asciidoc \
   \) | \
   while read f
   do
      h=${f/asciidoc/html}
      [ ! -f "$h" ] && __build_SLIDES "$f"
      [ "$f" -nt "$h" ] && __build_SLIDES "$f"
   done
}

_clean() {
   find . -maxdepth 1 -type f -name '*.html' -delete
}

_clean_all() {
   _clean
   rm -rf asciidoctor-backends dzslides
}

cd "$basedir"
_$op
