= Preparando a comunicação entre HOST e VM
:author: Paulo Jerônimo
:email: pj@paulojeronimo.info
:experimental:

Logue-se na console do CentOS (usuário/senha: +aluno+/+@lun0123+).

Se seu teclado não estiver configurado adequadamente, você pode executar o comando +loadkeys+. Por exemplo, se o seu teclado for +br-abnt2+, execute:
[source,bash]
----
$ sudo loadkeys br-abnt2
----
Essa configuração, contudo, não sobreviverá a um reboot! Se quiser mantê-la de forma permanente, execute:
[source,bash]
----
$ sudo sed -i 's/\(KEYTABLE=\).*/\1"br-abnt2"/g' /etc/sysconfig/keyboard
$ cat !$
----
Instale o VirtualBox Guest Additions:
[source,bash]
----
$ sudo yum -y install gcc kernel-devel-`uname -r`
$ sudo mount /dev/sr1 /mnt
$ sudo /mnt/VBoxLinuxAdditions.run
----
Se você estiver configurando essa VM num ambiente em que a Internet é acessada através de um proxy, execute:
[source,bash]
----
$ d=curso-jboss/dotfiles/Scripts; f=configurar-proxy
$ scp base:~/$d/$f .; vim $f
$ ./$f
$ logout
# refaça seu login ...
----
Instale o Git:
[source,bash]
----
$ sudo yum -y install git
----
Baixe o projeto livro-jboss no diretório +~/curso-jboss+ e mude para ele:
[source,bash]
----
$ git clone https://github.com/paulojeronimo/livro-jboss.git curso-jboss
$ cd !$
----
Baixe e instale o projeto dotfiles:
[source,bash]
----
$ git clone https://github.com/paulojeronimo/dotfiles.git
$ dotfiles/install
$ rm ~/.gitconfig
$ logout
# refaça se login ...
----
Inicie a gravação da sessão 1:
[source,bash]
----
$ sessao=~/curso-jboss/laboratorios/centos-pos-install/1
$ gravar $sessao
----
Conecte-se a +base+ criando um túnel reverso para a porta 3333:
[source,bash]
----
$ ssh -R 3333:localhost:22 base
----
Instale a chave pública do usuário +aluno+ da máquina +base+ e, em seguida, acesse a +vm-centos+ utilizando o túnel criado:
[source,bash]
----
$ ssh-copy-id -p 3333 localhost
$ ssh -p 3333 localhost
----
Gere o par de chaves para o aluno, na máquina vm-centos, e copie sua chave pública para a máquina +base+:
[source,bash]
----
$ ssh-keygen
$ ssh-copy-id base
----

Você está na máquina vm-centos, correto? As voltas do SSH te deixaram tonto? Rsrs... ;)

Giramos para um lado né!? Agora, vamos girar pro outro ... hehehe
[source,bash]
----
$ logout
$ logout
----
Encerre e copie a sessão 1 para a máquina +base+:
[source,bash]
----
$ exit
$ cat $sessao/sessao | \
ssh base bash -c ":; mkdir -p $sessao; cd $sessao; cat - > sessao"
----
Observe a estrutura de diretórios já montada para +~/curso-jboss+:
[source,bash]
----
$ sudo yum -y install tree
$ tree ~/curso-jboss | less
----
Desligue a vm-centos e aguarde seu shutdown:
[source,bash]
----
$ sudo shutdown -h now
----
De volta ao console da +base+, inicie a gravação da sessão 2:
[source,bash]
----
$ gravar ~/curso-jboss/laboratorios/centos-pos-install/2
----
Agora vamos "plugar" uma nova interface de rede na vm-centos. Isso será útil para evitarmos o uso do túnel reverso utilizamos agora a pouco. Ela também será útil nos laboratórios de JBoss em que formos levantar mais de uma instância.

Comande:
[source,bash]
----
$ VBoxManage hostonlyif create
$ VBoxManage hostonlyif ipconfig vboxnet0 --ip 192.168.0.253 --netmask 255.255.255.0
$ VBoxManage list hostonlyifs
$ VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet0
$ VBoxManage list dhcpservers
$ VBoxManage modifyvm vm-centos --nic2 hostonly --hostonlyadapter2 vboxnet0
----
Configure o arquivo +/etc/hosts+ adicionando a +vm-centos+:
[source,bash]
----
$ f=/etc/hosts; sudo sed -i '/vm-centos/d' $f
$ echo -e "192.168.0.254\tvm-centos" | sudo tee -a $f
$ grep vm-centos $f
----
Inicie novamente a VM:
[source,bash]
----
$ VBoxManage startvm vm-centos
----
Encerre a gravação da sessão 2:
[source,bash]
----
$ exit
----
Faça o login no console da VM. Em seguida, inicie a gravação da sessão 3:
[source,bash]
----
$ sessao=~/curso-jboss/laboratorios/centos-pos-install/3
$ gravar $sessao
----
Configure um IP estático para a interface eth1:
[source,bash]
----
$ cat<<'EOF' | sudo tee /etc/sysconfig/network-scripts/ifcfg-eth1
DEVICE=eth1
BOOTPROTO=static
IPADDR=192.168.0.254
PREFIX=24
GATEWAY=192.168.0.254
EOF
----
Reinicie os serviços de rede e verifique os IPs:
[source,bash]
----
$ sudo service network restart
$ sudo ip a s
----
Encerre e copie a sessão 3 para a +base+:
[source,bash]
----
$ exit
$ !?ssh base bash
----
Volte para o console da +base+ e inicie a sessão 4:
[source,bash]
----
$ gravar ~/curso-jboss/laboratorios/centos-pos-install/4
----
Teste um comando remoto (nenhuma senha deverá ser solicitada):
[source,bash]
----
$ ssh vm-centos date
----
Percebe a demora no estabelecimento da conexão SSH? Vamos, agora, resolver isso. Execute os passos apresentados em link:../fix-ssh-slow-connection/["Resolvendo o problema da lentidão na conexão com o SSH"].

Desligue novamente a VM _e aguarde até que ela esteja desligada antes de executar o próximo comando_:
[source,bash]
----
$ VBoxManage controlvm vm-centos acpipowerbutton
----
Agora, faça um snapshot da VM para caso precisemos voltar até o ponto em que chegamos:
[source,bash]
----
$ VBoxManage snapshot vm-centos take centos-pos-install
----

Encerre a sessão 4:
[source,bash]
----
$ exit
----
