= Instalando o CentOS num ambiente virtualizado (VirtualBox)
:author: Paulo Jerônimo
:email: pj@paulojeronimo.info

== Instalando e/ou configurando o Apache
Após essa instalação e/ou configuração do Apache, as seguintes URLs deverão estar acessíveis:

* http://localhost/~aluno/centos
* http://localhost/~aluno/ks

=== No OS X:
Leia a página http://blog.ladoservidor.com/2013/01/web-sharing-no-os-x-mountain-lion.html e execute:
[source,bash]
----
$ sudo bash -c '
cat > /etc/apache2/users/$SUDO_USER.conf <<EOF 
<Directory "/Users/$SUDO_USER/Sites/">
     Options Indexes MultiViews FollowSymLinks
     AllowOverride All
     Order allow,deny
     Allow from all
</Directory>
EOF
'
$ sudo apachectl restart
$ sudo defaults write /System/Library/LaunchDaemons/org.apache.httpd \
Disabled -bool false
$ d=~/Sites; mkdir -p $d && echo "Oi! Conseguiu! \o/" > $d/oi.txt; \
open http://localhost/~`whoami`/oi.txt
$ cd ~/Sites/
$ ln -s ~/curso-jboss/mirrors/CentOS/6.5/i386/mirror centos
$ ln -s ~/curso-jboss/mirrors/CentOS/6.5/i386/vm/ks.base ks
----

=== No Fedora:
Se você seguiu meus passos desde a http://a.paulojeronimo.info/tutoriais/fedora-mac/index.html[instalação do Fedora], seu Apache já deverá estar instalado. Caso contrário, retorne ao seu usuário e faça a http://a.paulojeronimo.info/tutoriais/fedora-mac/index.html#toc26[instalação do Apache]. Não se esqueça que, para recomeçar esse laboratório, você deverá estar logado como +aluno+. Então, nesse ponto, será necessário configurar um diretório público (via HTTP) para o usuário +aluno+. Antes disso, porém, execute:
[source,bash]
----
$ logout # para retonar ao seu usuário antes de se logar como aluno
$ xhost +
$ sudo su - aluno
$ export DISPLAY=:0
----
Em seguida:
[source,bash]
----
$ sudo chmod 755 $HOME
$ ls -ld $HOME
$ mkdir ~/public_html
$ cd !$
$ d=~/curso-jboss/mirrors/CentOS/6.5/i386
$ ln -s $d/mirror centos
$ ln -s $d/vm/ks.base ks
$ firefox http://localhost/~aluno/ &> /dev/null &
----
Observe que o SELinux poderá bloquear o acesso do servidor HTTP aos diretórios necessários. Nesse caso, serão notificados avisos de alerta. A forma mais simples de resolver esse problema é desabilitar, temporariamente o SELinux. Então, se necessário, faça isso:
[source,bash]
----
$ sudo setenforce 0
$ sudo getenforce
----
Em seguida, dê um refresh no browser e verifique se os links, agora, estão funcionando. A configuração acima, como eu disse, é temporária! Mais a frente faremos os ajustes corretos para que o SELinux não bloqueie o acesso os diretórios e, ainda assim, permaneça fazendo o seu papel de segurança.

== Instalando o VirtualBox
=== No OS X:
Baixe e instale a versão mais atual disponível para download. Link para o download: https://www.virtualbox.org/wiki/Downloads

=== No Fedora:
Baixe e instale a versão mais atual disponível para download. _Como exemplo, siga os passos apresentados em http://a.paulojeronimo.info/tutoriais/fedora-mac/index.html#toc31 mas esteja atento pois a versão instalada nesse documento pode não ser a mais atual_.

== Criando a VM
Execute o script vbox. Ele criará a VM:
[source,bash]
----
$ mkdir ~/curso-jboss/vms
$ ~/curso-jboss/mirrors/CentOS/6.5/i386/vm/vbox
----

.Nota para o instrutor:
[NOTE]
======
Em sua máquina não há espaço em disco na partição +/+. A primeira linha dos comandos apresentados acima deve ser executada da seguinte forma:

* No OS X:
[source,bash]
----
$ d=/Volumes/data/vms-aluno; mkdir -p $d; cd ~/curso-jboss && ln -s $d vms
----
* No Fedora:
[source,bash]
----
$ d=/data/pj/vms-aluno; sudo bash -c "mkdir -p $d && chown aluno: $d"; cd ~/curso-jboss && ln -s $d vms
----
======

== Iniciando a VM e aguardando a instalação do CentOS
Para iniciar a VM, execute:
[source,bash]
----
$ VBoxManage startvm vm-centos
----
Ao ser apresentado o prompt do Grub, adicione +ks=http://10.0.2.2/~aluno/ks+ a sua linha de inicialização. Para isso, pressione <Tab>, edite e, por fim, pressione <Enter> continuar o boot.

O processo de instalação da VM será realizado sem nenhuma intervenção.

Apenas ao final da instalação, você será questionado se deseja mudar o hostname da máquina (vm-centos) e/ou o formato do teclado. Contudo, se não você não estiver atento ao momento em que isso for solicitado (são apenas 5 segundos para responder), a instalação prosseguirá.

Aguarde a finalização do processo. Ao receber a mensagem de conclusão da instalação, "remova" o CD de instalação, digitando esse comando no console da base:
[source,bash]
----
$ VBoxManage storageattach vm-centos \
--storagectl "IDE Controller" \
--port 1 --device 0 --type dvddrive --medium emptydrive
----

Pressione <Enter> no console da VM para que ela seja reinicializada.

.Notas para o instrutor:
[NOTE]
======
Aproveitar o tempo da instalação e começar a falar sobre o arquivo de kickstart do CentOS! ;)
Se for necessário remover a +vm-centos+, por ter ocorrido algum erro em sua criação, executar:
[source,bash]
----
$ VBoxManage unregistervm vm-centos --delete
----
======
