= Instalando o CentOS num ambiente virtualizado (VirtualBox)
:author: Paulo Jerônimo
:email: pj@paulojeronimo.info

== Instalando e/ou configurando o Apache
Após essa instalação e/ou configuração do Apache, as seguintes URLs deverão estar acessíveis:

* http://localhost/~aluno/centos
* http://localhost/~aluno/ks

Se você seguiu meus passos desde a http://a.paulojeronimo.info/tutoriais/fedora-mac/index.html[instalação do Fedora], seu Apache já deverá estar instalado. Caso contrário, retorne ao seu usuário e faça a http://a.paulojeronimo.info/tutoriais/fedora-mac/index.html#toc30[instalação do Apache]. Não se esqueça que, para recomeçar esse laboratório, você deverá estar logado como +aluno+. Então, nesse ponto, será necessário configurar um diretório público (via HTTP) para o usuário +aluno+. Antes disso, porém, execute:
[source,bash]
----
$ logout # para retonar ao seu usuário antes de se logar como aluno
$ xhost +
$ sudo su - aluno
----
Em seguida:
[source,bash]
----
$ sudo chmod 755 $HOME
$ ls -ld $HOME
$ mkdir ~/public_html
$ cd !$
$ ln -s ~/curso-jboss/mirrors/CentOS/6.5/i386/mirror centos
$ curl -LO https://raw.githubusercontent.com/paulojeronimo/\
livro-jboss/master/laboratorios/centos-install/ks
$ mv ks ~/curso-jboss
$ ln -s !$/ks
$ firefox http://localhost/~aluno/ &> /dev/null &
----
Observe que o SELinux poderá bloquear o acesso do servidor HTTP aos diretórios necessários. Nesse caso, serão notificados avisos de alerta. A forma mais simples de resolver esse problema é desabilitar, temporariamente o SELinux. Então, se necessário, faça isso:
[source,bash]
----
$ sudo setenforce 0
$ sudo getenforce
----
Em seguida, dê um refresh no browser e verifique se os links, agora, estão funcionando. A configuração acima, como eu disse, é temporária! Mais a frente faremos os ajustes corretos para que o SELinux não bloqueie o acesso os diretórios e, ainda assim, permaneça fazendo o seu papel de segurança.

== Instalando o VirtualBox
Baixe e instale a versão mais atual disponível para download. _Como exemplo, siga os passos apresentados em http://a.paulojeronimo.info/tutoriais/fedora-mac/index.html#toc31 mas esteja atento pois a versão instalada nesse documento pode não ser a mais atual_.

== Criando a VM
A seguir, baixe e execute o script vm-centos.sh:
[source,bash]
----
$ cd ~/curso-jboss
$ f=vm-centos.sh
$ curl -LO https://raw.githubusercontent.com/paulojeronimo/livro-jboss/master/\
laboratorios/centos-install/$f && chmod +x $f && ./$f
----
.Nota para o instrutor:
[NOTE]
======
Em sua máquina não há espaço em disco na partição +/+ para acomodar o crescimento do disco da VM. Você deverá movê-la e criar um link para sua nova localização, da seguinte forma:
[source,bash]
----
$ d=/data/aluno/VirtualBox\ VMs
$ sudo bash -c "mkdir -p \"$d\" && chown -R aluno: `dirname \"$d\"`"
$ mv vm-centos "$d" && ln -s "$d"/vm-centos
----
======

== Iniciando a VM e aguardando a instalação do CentOS
Para iniciar a VM, execute:
[source,bash]
----
$ VBoxManage startvm vm-centos
----
Ao ser apresentado o prompt do Grub, adicione +ks=http://10.0.2.2/~aluno/ks+ a sua linha de inicialização. Para isso, pressione <Tab>, edite e, por fim, pressione <Enter> continuar o boot.

O processo de instalação da VM será realizado sem nenhuma intervenção.

Apenas ao final da instalação, você será questionado se deseja mudar o hostname da máquina (vm-centos) e/ou o formato do teclado. Contudo, se não você não estiver atento ao momento em que isso for solicitado, são apenas 5 segundos para responder, a instalação prosseguirá.

Aguarde a finalização do processo. Ao receber a mensagem de conclusão da instalação, "remova" o CD de instalação, digitando este comando no console da base:
[source,bash]
----
$ VBoxManage storageattach vm-centos \
--storagectl "IDE Controller" \
--port 1 --device 0 --type dvddrive --medium emptydrive
----

Pressione <Enter> no console da VM para que ela seja reinicializada.

.Notas para o instrutor:
[NOTE]
======
. Aproveite o tempo da instalação e começe a falar sobre o arquivo de kickstart do CentOS! ;)
. Se for necessário remover a +vm-centos+, por ter ocorrido algum erro em sua criação, execute:
[source,bash]
----
$ VBoxManage unregistervm vm-centos --delete
----
======
