= Instalando o CentOS num ambiente virtualizado (VirtualBox)
:author: Paulo Jerônimo
:email: pj@paulojeronimo.info

== Configure seu servidor web
* Após essa configuração, as seguintes URLs deverão estar acessíveis:
** http://localhost/~aluno/centos
** http://localhost/~aluno/ks

=== No OS X:
* Leia a página http://blog.ladoservidor.com/2013/01/web-sharing-no-os-x-mountain-lion.html e execute:
[source,bash]
----
$ sudo bash -c '
cat > /etc/apache2/users/$SUDO_USER.conf <<EOF 
<Directory "/Users/$SUDO_USER/Sites/">
     Options Indexes MultiViews FollowSymLinks
     AllowOverride All
     Order allow,deny
     Allow from all
</Directory>
EOF
'
$ sudo apachectl restart
$ sudo defaults write /System/Library/LaunchDaemons/org.apache.httpd \
Disabled -bool false
$ d=~/Sites; mkdir -p $d && echo "Oi! Conseguiu! \o/" > $d/oi.txt; \
open http://localhost/~`whoami`/oi.txt
$ cd ~/Sites/
$ ln -s ~/curso-jboss/mirrors/CentOS/6.5/i386/mirror centos
$ ln -s ~/curso-jboss/mirrors/CentOS/6.5/i386/vm/ks.base ks
----

== Instale a versão 4.3.8 do VirtualBox
=== No OS X:
* Baixe e instale. Link: http://download.virtualbox.org/virtualbox/4.3.8/VirtualBox-4.3.8-92456-OSX.dmg

=== No Fedora:
* Se o VirtualBox ainda não tiver sido instalado, siga os passos apresentados em http://a.paulojeronimo.info/tutoriais/fedora-mac/index.html#toc27. Em seguida, execute:

== Crie a VM
* Execute o script vbox. Ele criará a VM:
[source,bash]
----
$ mkdir ~/curso-jboss/vms
$ ~/curso-jboss/mirrors/CentOS/6.5/i386/vm/vbox
----

Nota para o instrutor: em sua máquina não há espaço em disco no Volume do Mac OS X. A primeira linha dos comandos apresentados acima deve ser executada da seguinte forma:
[source,bash]
----
$ d=/Volumes/data/vms-aluno; mkdir -p $d; cd ~/curso-jboss && ln -s $d vms
----

== Inicie a VM e aguarde a instalação
* Ao iniciar a VM, adicione 'ks=http://10.0.2.2/~aluno/ks' (sem os apóstrofos) a linha de inicialização do grub (pressione <Tab> para isso) e, em seguida, pressione <Enter>
* O processo de instalação da VM será realizado sem nenhuma intervenção. Aguarde sua finalização e, ao receber a mensagem de conclusão da instalação, remova o CD de instalação e pressione <Enter> para que a máquina seja reinicializada.

.Nota para o instrutor:
[NOTE]
==================
Aproveitar o tempo da instalação e começar a falar sobre o arquivo de kickstart do CentOS! ;)
==================
