= Laboratório: Fazendo um mirror do CentOS
:author: Paulo Jerônimo
:email: pj@paulojeronimo.info

== Crie e logue-se como usuário aluno
* O usuário aluno deverá ter poderes administrativos;
* No Fedora, execute:
[source,bash]
----
$ sudo useradd -m -s /bin/bash -G wheel aluno
$ echo 'aluno:@lun0123' | sudo chpasswd
$ sudo su - aluno
----

== Crie seu mirror 
* O último comando dessa seção deverá demorar bastante pois será realizado o download de cerca de 9GB de arquivos;
* Crie o diretório do curso:
[source,bash]
----
$ mkdir ~/curso-jboss
$ cd !$
----
* Se você ainda não tiver o Git instalado, execute o conjunto de comandos a seguir. Do contrário, pule esses comandos e siga as próximas instruções.
[source,bash]
----
$ curl -L -O https://github.com/paulojeronimo/mirrors/archive/master.zip
$ unzip master.zip
$ ln -s mirrors-master mirrors
$ cd !!:3
----
* Se você possui o Git e saltou as instruções acima, execute:
[source,bash]
----
$ git clone https://github.com/paulojeronimo/mirrors.git
$ cd mirrors
----
* A execução do comando a seguir deverá demorar bastante (ele criará seu mirror utilizando o rsync para baixar o CentOS a partir de um mirror já existente).
[source,bash]
----
$ CentOS/6.5/i386/mirror.sh
----

== Extras 
* Você poderá executar as linhas a seguir quando já tiver seu mirror num HD externo;
** Se o comando anterior estiver sendo executado, interrompa-o com um <Ctrl+C>;
** Plugue seu HD externo na USB;
** Crie o arquivo +.bin/config+ para informar a localização do diretório que contém seus mirrors. Para isso, copie o arquivo de configuração de exemplo (+.bin/config.sample+) e ajuste-o conforme o teu ambiente.
[source,bash]
----
$ cat .bin/config.sample 
LOCAL_MIRRORS_DIR_ON_DARWIN=/Volumes/data/mirrors
LOCAL_MIRRORS_DIR_ON_LINUX=/data/mirrors
EXTERNAL_MIRRORS_DIR_ON_DARWIN=/Volumes/PJ-HFS/mirrors
EXTERNAL_MIRRORS_DIR_ON_LINUX=/run/media/$SUDO_USER/PJ-HFS/mirrors
$ cp .bin/config.sample .bin/config
$ vim .bin/config
----
* Execute os comandos abaixo (maiores explicações no vídeo do laboratório):
[source,bash]
----
$ rm -rf CentOS/6.5/i386/mirror
$ .bin/create-links
$ ls -la CentOS/6.5/i386/mirror
$ du -hsc CentOS/6.5/i386/mirror/
$ rm -rf CentOS/6.5/i386/mirror/updates/
$ .bin/mirror-from-external-hd.CentOS-6.5-i386
$ du -hsc CentOS/6.5/i386/mirror/
$ CentOS/6.5/i386/mirror.sh
$ .bin/mirror-to-external-hd.CentOS-6.5-i386
-----

* Desplugue o HD externo (seu mirror local, agora, também está salvo nele!)
